import React, { useEffect, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import * as maplibregl from 'maplibre-gl'
import 'maplibre-gl/dist/maplibre-gl.css'
import './styles.css'
import data from './data/trip.json'

const tabs=['Now','Plan','Map','Group','More']
const byId=(arr,id)=>arr.find(x=>x.id===id)
const fmtDate=d=>new Intl.DateTimeFormat('en-IN',{weekday:'short',day:'numeric',month:'short'}).format(new Date(`${d}T12:00:00+05:30`))

function App(){
  const [tab,setTab]=useState('Now')
  const [day,setDay]=useState('2026-09-14')
  const [installPrompt,setInstallPrompt]=useState(null)
  useEffect(()=>{const h=e=>{e.preventDefault();setInstallPrompt(e)};window.addEventListener('beforeinstallprompt',h);if('serviceWorker'in navigator)navigator.serviceWorker.register('/mumbai-trip/sw.js');return()=>window.removeEventListener('beforeinstallprompt',h)},[])
  return <div className="app-shell"><header><div><span className="eyebrow">MUMBAI · 14–17 SEP</span><h1>TripOS</h1></div><div className="status-dot">shared</div></header><main>
    {tab==='Now'&&<Now/>}{tab==='Plan'&&<Plan day={day} setDay={setDay}/>} {tab==='Map'&&<MapView/>}{tab==='Group'&&<Group/>}{tab==='More'&&<More installPrompt={installPrompt} setInstallPrompt={setInstallPrompt}/>} 
  </main><button className="fab" onClick={()=>alert('Tell ChatGPT what to add. Shared trip edits are committed to GitHub, not saved only on this phone.')}>＋ Add</button><nav>{tabs.map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}><span>{icon(t)}</span>{t}</button>)}</nav></div>
}
function Now(){const fixed=data.activities.filter(a=>a.timing.type==='fixed').sort((a,b)=>(a.date+a.timing.start).localeCompare(b.date+b.timing.start));const next=fixed[0];const place=next.placeId&&byId(data.places,next.placeId);return <section className="stack"><div className="hero-card"><span className="eyebrow">NEXT FIXED ITEM</span><h2>{next.title}</h2><div className="big-time">{fmtDate(next.date)} · {next.timing.start}</div><p>{next.notes[0]}</p><div className="actions">{place?.googleMapsUrl&&<a href={place.googleMapsUrl} target="_blank" rel="noreferrer">Navigate</a>}<button onClick={()=>alert('Open Plan from the bottom navigation.')}>Plan</button></div></div><RiskStrip/><section><h3>Trip at a glance</h3><div className="mini-grid"><Stat k="4" v="travellers on rail tickets"/><Stat k="2" v="fixed trains"/><Stat k="1" v="fixed reservation"/><Stat k="3" v="days in Mumbai"/></div></section><section><h3>Next anchors</h3>{fixed.map(a=><TimelineItem key={a.id} a={a}/>)}</section></section>}
function RiskStrip(){return <div className="risk"><b>Needs refresh before departure</b><span>Ganeshotsav crowd, road restrictions, weather and venue hours.</span></div>}
function Stat({k,v}){return <div className="stat"><strong>{k}</strong><span>{v}</span></div>}
function Plan({day,setDay}){const dates=['2026-09-14','2026-09-15','2026-09-16','2026-09-17'];const items=data.activities.filter(a=>a.date===day).sort((a,b)=>(a.timing.start||a.timing.earliest||'99:99').localeCompare(b.timing.start||b.timing.earliest||'99:99'));return <section className="stack"><div className="day-tabs">{dates.map(d=><button className={day===d?'active':''} key={d} onClick={()=>setDay(d)}>{new Date(`${d}T12:00:00+05:30`).getDate()}</button>)}</div><div><span className="eyebrow">{fmtDate(day)}</span><h2>{day==='2026-09-17'?'Return day':'Day plan'}</h2></div>{items.length?items.map(a=><TimelineItem a={a} key={a.id}/>):<div className="empty">No committed activities yet. Add candidates through ChatGPT, then promote the ones you want.</div>}</section>}
function TimelineItem({a}){const p=a.placeId&&byId(data.places,a.placeId);const time=a.timing.start||`${a.timing.earliest||'flex'}–${a.timing.latest||''}`;return <article className="timeline"><div className={`pin ${a.timing.type}`}></div><div><div className="row"><span className="time">{time}</span><span className="badge">{a.timing.type}</span></div><h4>{a.title}</h4>{p&&<p>{p.name}</p>}<p className="muted">{a.notes?.[0]}</p><div className="avatars">{a.participants.map(id=><span key={id} title={byId(data.members,id)?.name}>{byId(data.members,id)?.initials}</span>)}</div></div></article>}
function MapView(){const ref=useRef();const mapRef=useRef();useEffect(()=>{if(mapRef.current)return;const m=new maplibregl.Map({container:ref.current,style:'https://tiles.openfreemap.org/styles/liberty',center:[72.84,19.02],zoom:10.3});mapRef.current=m;data.places.filter(p=>p.latitude&&p.longitude).forEach(p=>new maplibregl.Marker({color:'#174a8b'}).setLngLat([p.longitude,p.latitude]).setPopup(new maplibregl.Popup().setHTML(`<strong>${p.name}</strong><br>${p.category}`)).addTo(m));return()=>{m.remove();mapRef.current=null}},[]);return <section className="map-wrap"><div className="map-head"><span className="eyebrow">OPEN MAP</span><h2>Trip geography</h2><p>Static trip coordinates with live tiles when online. Use Google Maps links for navigation.</p></div><div ref={ref} className="map"></div></section>}
function Group(){return <section className="stack"><div><span className="eyebrow">GROUP</span><h2>People</h2><p className="muted">Shared state is read-only in the PWA. Changes go through ChatGPT → GitHub → Pages.</p></div><div className="people">{data.members.map(m=><div className="person" key={m.id}><span>{m.initials}</span><div><b>{m.name}</b><small>{m.id==='pratham'?'Sea Lounge booking holder':'trip member'}</small></div></div>)}</div></section>}
function More({installPrompt,setInstallPrompt}){const install=async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;setInstallPrompt(null)};return <section className="stack"><div><span className="eyebrow">SYSTEM</span><h2>Trip controls</h2></div>{installPrompt&&<button className="primary" onClick={install}>Install TripOS</button>}<div className="settings"><div><b>Offline core</b><span>Enabled after first successful load</span></div><div><b>Canonical data</b><span>src/data/trip.json</span></div><div><b>Public-safe mode</b><span>Sensitive ticket references excluded</span></div><div><b>Deployment</b><span>GitHub Pages · HTTPS</span></div></div></section>}
function icon(t){return ({Now:'◉',Plan:'≡',Map:'⌖',Group:'◎',More:'•••'})[t]}
createRoot(document.getElementById('root')).render(<App/>)
